# Generated by nixos-generate-config or nixos-facter.
# Populate this file by running: nixos-generate-config --show-hardware-config
# on the target machine (Lenovo ThinkPad T480).
{ ... }:
{
  # Hardware configuration for Lenovo ThinkPad T480 (shiina).
  # Replace this with the output of: nixos-generate-config --show-hardware-config
}
