users:
    root:
        password_hash: ENC[AES256_GCM,data:LWK6bHtfhPRLqmSvHljDU2zmZFJ23oYfAkpk8Aq8MRXh3VorsaAzDA1/YhwA9cHvouQXq+kG4i+uMETkF78IGVPO2eo7plKMAA==,iv:v7qfdoaY7JSk1NQCw43dRec/8n0sj9joF+6BNFIGl6s=,tag:kj58Ukgj/eIYmgB3WzAoew==,type:str]
    kurisu:
        password_hash: ENC[AES256_GCM,data:473kwR9OeoNTqSQ/YjWITtRxSH/JRkQfnkq73rUgEeGqkNefy/tJSpCaC32Qyw9M53UEeJ2RzZ5akl6Lt7U0W4fP1+6NSEBiIg==,iv:yrAWvMFT+Udq+ihtnX/wfUN/xRkaCJvO/L2WrK9qKf4=,tag:VAhSMxfeAhFE8PwO+8TIDg==,type:str]
sops:
    age:
        - recipient: age1hfsr0yvs6nwr2ecffcrp2pdvztx8lgfnmd7t8whr53u3lczzcfaq0rrs6z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQWtYbTJmVmZnRmJCamxh
            eHZQMk9kWUZTMTlpOWxvelF2aEdPNVl6eENvClBUYWkvVThGQ0ltUlZia3MxS0dp
            VUFEYkYvMi9yNmxRbzEvWWhUSm54d1EKLS0tIGxuZGdtMFdReXdrVytNS3Z3NEtu
            ck4yakVULzVtVkkyUTFLQXE4VFNkVncK6QhfZfVsFqmEHKNExZYKVXfwTUt4gA7w
            QApeNJ+7KmE77wtzmBX60lhoD1whBQQEDrgZSvOqxOiKhY3dHKnMoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age154ausyv0u0lscdxlurm29wnktw0w694z6q87xnd5l5laj2xrp98qrkxc74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTE4xWkhJK2FZNUtKV1JP
            MU9jMm9wZ0dhcm5URjhRVkltUDY2VnlJMkdJCmlXTkNnRHFYbmIxMXIrc0pzM3R1
            M1AxYVQ4WHVpdm9yRDZRQVIxZ0tlNlkKLS0tIERQWXBUaHo0cy9NaWIzenRBQkV6
            T1UyZHBad0V3cmxKM1luTFNISWVoNU0Klaho/02lcqbWvYPU37PitwuPhyenREpU
            BmU4iHUQ+ZivyWunoBH6Ut4pgdsOzGti+U0/D29oY9yysSxBak+gAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T11:43:20Z"
    mac: ENC[AES256_GCM,data:q23+VsHuj4Mo1GOEpgx3x+cjXH3lT9qATStTMwlVlUfe2hDp7ipjdvYvxNXepBhRp6Dpq6X0BDc5XYp/t6A+FZcQ4V0wh/CiWQNmVXgPmbkP/URQ0eNqOrF3D8+mbpmrYqiy/jvmjFjaB5nHRL9T1hnbY0lO79/U5r66X1NuvoM=,iv:Gr774eqhm2Oie7bpH1R+/3g+jS/1EyDpFDfAXnQfnC8=,tag:pYGglTgf08jzw3J62hnnsw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
